# site
title: Adam Sulzdorf-Liszkiewicz
baseurl: 
url: "http://liszkiewicz.github.io"
favicon: "/assets/sample/ico.png"
g_analytics: UA-12345678-1

# bio
header: Adam Sulzdorf-Liszkiewicz, Selected Work (2007-2018)
desc: >
  Adam is the Chief Executive Officer at RUST LTD., and the Director of the Playwork Research Lab. He is a Visiting Assistant Professor of Media Arts and Culture at Occidental College.

# posts
date_format: "%Y"
post_title: Project Title
post_date: Year
post_cat: Category

# post detail
prev-next: true

# build settings
markdown: kramdown
# theme: louie
exclude:
  - Gemfile
  - Gemfile.lock
