# site
title: Adam Sulzdorf-Liszkiewicz
baseurl: 
url: "http://liszkiewicz.github.io"
favicon: "/assets/sample/ico.png"
g_analytics: UA-12345678-1

# bio
header: Adam Sulzdorf-Liszkiewicz, Selected Work (2007-2018)
desc: >
  Adam is a designer, educator, and writer who lives in Los Angeles, CA. He is the author of a full-length collection of digital poetry and games, AFEELD, which was published in 2017 by the Collaboratory for Digital Discourse and Culture at Virginia Tech. Since 2008, he has held academic positions alongside his creative practice, most recently at Occidental College, USC, and UCLA. He is currently Chief Executive Officer of the award-winning game design and virtual reality studio, RUST LTD.

# posts
date_format: "%Y"
post_title: Project Title
post_date: Year
post_cat: Category

# post detail
prev-next: true

# build settings
markdown: kramdown
# theme: louie
exclude:
  - Gemfile
  - Gemfile.lock
